<?php return array(
    'root' => array(
        'pretty_version' => 'dev-TL-28246/13',
        'version' => 'dev-TL-28246/13',
        'type' => 'metapackage',
        'install_path' => __DIR__ . '/../',
        'aliases' => array(),
        'reference' => '712f27eeda7e8c1e3c04cdb1f961f2bfcf5b98fa',
        'name' => 'totara/totara_require',
        'dev' => true,
    ),
    'versions' => array(
        'box/spout' => array(
            'pretty_version' => 'v2.7.3',
            'version' => '2.7.3.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../box/spout',
            'aliases' => array(),
            'reference' => '3681a3421a868ab9a65da156c554f756541f452b',
            'dev_requirement' => false,
        ),
        'ezyang/htmlpurifier' => array(
            'pretty_version' => 'v4.13.0',
            'version' => '4.13.0.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../ezyang/htmlpurifier',
            'aliases' => array(),
            'reference' => '08e27c97e4c6ed02f37c5b2b20488046c8d90d75',
            'dev_requirement' => false,
        ),
        'phpmailer/phpmailer' => array(
            'pretty_version' => 'v6.5.1',
            'version' => '6.5.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../phpmailer/phpmailer',
            'aliases' => array(),
            'reference' => 'dd803df5ad7492e1b40637f7ebd258fee5ca7355',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php73' => array(
            'pretty_version' => 'v1.22.1',
            'version' => '1.22.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php73',
            'aliases' => array(),
            'reference' => 'a678b42e92f86eca04b7fa4c0f6f19d097fb69e2',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php74' => array(
            'pretty_version' => 'v1.22.1',
            'version' => '1.22.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php74',
            'aliases' => array(),
            'reference' => '577e147350331efeb816897e004d85e6e765daaf',
            'dev_requirement' => false,
        ),
        'symfony/polyfill-php80' => array(
            'pretty_version' => 'v1.22.1',
            'version' => '1.22.1.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../symfony/polyfill-php80',
            'aliases' => array(),
            'reference' => 'dc3063ba22c2a1fd2f45ed856374d79114998f91',
            'dev_requirement' => false,
        ),
        'totara/totara_require' => array(
            'pretty_version' => 'dev-TL-28246/13',
            'version' => 'dev-TL-28246/13',
            'type' => 'metapackage',
            'install_path' => __DIR__ . '/../',
            'aliases' => array(),
            'reference' => '712f27eeda7e8c1e3c04cdb1f961f2bfcf5b98fa',
            'dev_requirement' => false,
        ),
        'webonyx/graphql-php' => array(
            'pretty_version' => 'v0.13.2',
            'version' => '0.13.2.0',
            'type' => 'library',
            'install_path' => __DIR__ . '/../webonyx/graphql-php',
            'aliases' => array(),
            'reference' => '9fc4d114250271c37d9786a78d84549386f2be3c',
            'dev_requirement' => false,
        ),
    ),
);
