language: php

sudo: false

addons:
  postgresql: "9.6"

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache

php:
 - 7.1

env:
  - DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=pgsql MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=pgsql MOODLE_BRANCH=master
  - DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_33_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_34_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_35_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_36_STABLE
  - DB=mysqli MOODLE_BRANCH=MOODLE_37_STABLE
  - DB=mysqli MOODLE_BRANCH=master

matrix:
  include:
    - php: 5.5
      dist: trusty
      env: DB=pgsql MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 5.5
      dist: trusty
      env: DB=pgsql MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 5.6
      dist: trusty
      env: DB=pgsql MOODLE_BRANCH=MOODLE_32_STABLE
    - php: 5.5
      dist: trusty
      env: DB=mysqli MOODLE_BRANCH=MOODLE_30_STABLE
    - php: 5.5
      dist: trusty
      env: DB=mysqli MOODLE_BRANCH=MOODLE_31_STABLE
    - php: 5.6
      dist: trusty
      env: DB=mysqli MOODLE_BRANCH=MOODLE_32_STABLE

before_install:
  - cd ../..
  - composer selfupdate
  - composer create-project -n --no-dev moodlerooms/moodle-plugin-ci ci ^1
  - export PATH="$(cd ci/bin; pwd):$(cd ci/vendor/bin; pwd):$PATH"

install:
  - moodle-plugin-ci install

script:
  - moodle-plugin-ci phplint
  - moodle-plugin-ci phpcpd
  - moodle-plugin-ci phpmd
  - moodle-plugin-ci codechecker
  - moodle-plugin-ci csslint    # No CSS
  - moodle-plugin-ci shifter
  - moodle-plugin-ci jshint     # No JS
  - moodle-plugin-ci phpunit    # No tests yet
  - moodle-plugin-ci behat      # No tests yet

