<?php
// This file is part of Moodle - http://moodle.org/
//
// Moodle is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Moodle is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Moodle.  If not, see <http://www.gnu.org/licenses/>.

/**
 * This script fixed incorrectly deleted users.
 *
 * @package    core
 * @subpackage cli
 * @copyright  2013 Petr Skoda (http://skodak.org)
 * @license    http://www.gnu.org/copyleft/gpl.html GNU GPL v3 or later
 */

define('CLI_SCRIPT', true);

require(__DIR__.'/../../../config.php');
require_once($CFG->libdir.'/clilib.php');
require_once($CFG->dirroot . '/lib/adminlib.php');                                                                                                                                                  
require_once($CFG->dirroot . '/admin/tool/xmldb/actions/XMLDBAction.class.php');
require_once($CFG->dirroot . '/admin/tool/xmldb/actions/get_db_directories/get_db_directories.class.php');


// Now get cli options.
list($options, $unrecognized) = cli_get_params(
    array(
        'help'=>false,
        'path'=>'',
    ),
    array(
        'h' => 'help',
        'p' => 'path',
    )
);

if ($unrecognized) {
    $unrecognized = implode("\n  ", $unrecognized);
    cli_error(get_string('cliunknowoption', 'admin', $unrecognized));
}

if ($options['help']) {
    $help =
        "Given a path to an xmldb file, prints out what the content should be if regenerated by XMLDB

        Options:
        -h, --help            Print out this help
        -p, --path            Path to xmldb file
";

    echo $help;
    die;
}
$file = $options['path'];
$xmldb_file = new xmldb_file($file);
// Set the XML DTD and schema
$xmldb_file->setDTD($CFG->dirroot . '/lib/xmldb/xmldb.dtd');
$xmldb_file->setSchema($CFG->dirroot . '/lib/xmldb/xmldb.xsd');
// Set dbdir as necessary
if (!$xmldb_file->fileExists()) {
    mtrace("XMLDB file {$file} does not exist");
    exit(1);
}
// Load the XML contents to structure
if(!$xmldb_file->loadXMLStructure()) {
    mtrace("XMLDB file '{$file}' cannot be loaded, check the structure returned by this call for the error.");
    exit(1);
}
if(!$xmldb_file->isLoaded()) {
    mtrace("XMLDB file '{$file}' did not load correctly");
    exit(1);
}
$structure = $xmldb_file->getStructure();
if($structure) {
    print($structure->xmlOutput());
}
else {
    mtrace("XDMLDB file '{$file}' did not generate a valid structure");
    exit(1);
}
exit(0);
